//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria2Manager.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aria2Manager.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Advanced_Options {
            get {
                return ResourceManager.GetString("Advanced_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled Features 的本地化字符串。
        /// </summary>
        public static string Aria2_Features {
            get {
                return ResourceManager.GetString("Aria2_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Settings 的本地化字符串。
        /// </summary>
        public static string Aria2_Options {
            get {
                return ResourceManager.GetString("Aria2_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Servers 的本地化字符串。
        /// </summary>
        public static string Aria2_Servers {
            get {
                return ResourceManager.GetString("Aria2_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Status 的本地化字符串。
        /// </summary>
        public static string Aria2_Status {
            get {
                return ResourceManager.GetString("Aria2_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 update available 的本地化字符串。
        /// </summary>
        public static string Aria2_Update_Available {
            get {
                return ResourceManager.GetString("Aria2_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Version 的本地化字符串。
        /// </summary>
        public static string Aria2_Version {
            get {
                return ResourceManager.GetString("Aria2_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Website 的本地化字符串。
        /// </summary>
        public static string Aria2_Website {
            get {
                return ResourceManager.GetString("Aria2_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_all_proxy {
            get {
                return ResourceManager.GetString("Aria2Option_all-proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_all_proxy_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_all-proxy-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_all_proxy_user {
            get {
                return ResourceManager.GetString("Aria2Option_all-proxy-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Overwrite 的本地化字符串。
        /// </summary>
        public static string Aria2Option_allow_overwrite {
            get {
                return ResourceManager.GetString("Aria2Option_allow-overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Piece Length Change 的本地化字符串。
        /// </summary>
        public static string Aria2Option_allow_piece_length_change {
            get {
                return ResourceManager.GetString("Aria2Option_allow-piece-length-change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Resume 的本地化字符串。
        /// </summary>
        public static string Aria2Option_always_resume {
            get {
                return ResourceManager.GetString("Aria2Option_always-resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Async DNS 的本地化字符串。
        /// </summary>
        public static string Aria2Option_async_dns {
            get {
                return ResourceManager.GetString("Aria2Option_async-dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto File Renaming 的本地化字符串。
        /// </summary>
        public static string Aria2Option_auto_file_renaming {
            get {
                return ResourceManager.GetString("Aria2Option_auto-file-renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Save Interval 的本地化字符串。
        /// </summary>
        public static string Aria2Option_auto_save_interval {
            get {
                return ResourceManager.GetString("Aria2Option_auto-save-interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detach Seed Only Tasks 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_detach_seed_only {
            get {
                return ResourceManager.GetString("Aria2Option_bt-detach-seed-only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Hook After Hash Check 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_enable_hook_after_hash_check {
            get {
                return ResourceManager.GetString("Aria2Option_bt-enable-hook-after-hash-check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Local Peer Discovery (LPD) 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_enable_lpd {
            get {
                return ResourceManager.GetString("Aria2Option_bt-enable-lpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude BT Tracker Addresses 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_exclude_tracker {
            get {
                return ResourceManager.GetString("Aria2Option_bt-exclude-tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use * to match all addresses, comma separated 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_exclude_tracker_Tip {
            get {
                return ResourceManager.GetString("Aria2Option_bt-exclude-tracker_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External IP Address 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_external_ip {
            get {
                return ResourceManager.GetString("Aria2Option_bt-external-ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Encryption 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_force_encryption {
            get {
                return ResourceManager.GetString("Aria2Option_bt-force-encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash Check Before Seeding 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_hash_check_seed {
            get {
                return ResourceManager.GetString("Aria2Option_bt-hash-check-seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Saved Metadata 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_load_saved_metadata {
            get {
                return ResourceManager.GetString("Aria2Option_bt-load-saved-metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Open Files 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_max_open_files {
            get {
                return ResourceManager.GetString("Aria2Option_bt-max-open-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Peers 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_max_peers {
            get {
                return ResourceManager.GetString("Aria2Option_bt-max-peers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Metadata Only 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_metadata_only {
            get {
                return ResourceManager.GetString("Aria2Option_bt-metadata-only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Crypto Level 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_min_crypto_level {
            get {
                return ResourceManager.GetString("Aria2Option_bt-min-crypto-level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritize Piece 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_prioritize_piece {
            get {
                return ResourceManager.GetString("Aria2Option_bt-prioritize-piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Unselected Files 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_remove_unselected_file {
            get {
                return ResourceManager.GetString("Aria2Option_bt-remove-unselected-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Peer Speed Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_request_peer_speed_limit {
            get {
                return ResourceManager.GetString("Aria2Option_bt-request-peer-speed-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Require Crypto 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_require_crypto {
            get {
                return ResourceManager.GetString("Aria2Option_bt-require-crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Metadata 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_save_metadata {
            get {
                return ResourceManager.GetString("Aria2Option_bt-save-metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed Unverified 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_seed_unverified {
            get {
                return ResourceManager.GetString("Aria2Option_bt-seed-unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Stop Timeout When No Speed 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_stop_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_bt-stop-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT Tracker Addresses 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_tracker {
            get {
                return ResourceManager.GetString("Aria2Option_bt-tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT Tracker Connect Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_tracker_connect_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_bt-tracker-connect-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT Tracker Connection Interval 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_tracker_interval {
            get {
                return ResourceManager.GetString("Aria2Option_bt-tracker-interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT Tracker Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_tracker_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_bt-tracker-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comma separated 的本地化字符串。
        /// </summary>
        public static string Aria2Option_bt_tracker_Tip {
            get {
                return ResourceManager.GetString("Aria2Option_bt-tracker_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Certificate 的本地化字符串。
        /// </summary>
        public static string Aria2Option_check_certificate {
            get {
                return ResourceManager.GetString("Aria2Option_check-certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Integrity 的本地化字符串。
        /// </summary>
        public static string Aria2Option_check_integrity {
            get {
                return ResourceManager.GetString("Aria2Option_check-integrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional GET 的本地化字符串。
        /// </summary>
        public static string Aria2Option_conditional_get {
            get {
                return ResourceManager.GetString("Aria2Option_conditional-get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_conf_path {
            get {
                return ResourceManager.GetString("Aria2Option_conf-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_connect_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_connect-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console Log Level 的本地化字符串。
        /// </summary>
        public static string Aria2Option_console_log_level {
            get {
                return ResourceManager.GetString("Aria2Option_console-log-level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use UTF-8 for Content-Disposition 的本地化字符串。
        /// </summary>
        public static string Aria2Option_content_disposition_default_utf8 {
            get {
                return ResourceManager.GetString("Aria2Option_content-disposition-default-utf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue Download 的本地化字符串。
        /// </summary>
        public static string Aria2Option_continue {
            get {
                return ResourceManager.GetString("Aria2Option_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Daemon 的本地化字符串。
        /// </summary>
        public static string Aria2Option_daemon {
            get {
                return ResourceManager.GetString("Aria2Option_daemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deferred Input 的本地化字符串。
        /// </summary>
        public static string Aria2Option_deferred_input {
            get {
                return ResourceManager.GetString("Aria2Option_deferred-input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DHT (IPv4) File Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dht_file_path {
            get {
                return ResourceManager.GetString("Aria2Option_dht-file-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DHT (IPv6) File Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dht_file_path6 {
            get {
                return ResourceManager.GetString("Aria2Option_dht-file-path6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DHT Listen Port 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dht_listen_port {
            get {
                return ResourceManager.GetString("Aria2Option_dht-listen-port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DHT Message Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dht_message_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_dht-message-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dir {
            get {
                return ResourceManager.GetString("Aria2Option_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable IPv6 的本地化字符串。
        /// </summary>
        public static string Aria2Option_disable_ipv6 {
            get {
                return ResourceManager.GetString("Aria2Option_disable-ipv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk Cache 的本地化字符串。
        /// </summary>
        public static string Aria2Option_disk_cache {
            get {
                return ResourceManager.GetString("Aria2Option_disk-cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Result 的本地化字符串。
        /// </summary>
        public static string Aria2Option_download_result {
            get {
                return ResourceManager.GetString("Aria2Option_download-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dry Run 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dry_run {
            get {
                return ResourceManager.GetString("Aria2Option_dry-run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DSCP 的本地化字符串。
        /// </summary>
        public static string Aria2Option_dscp {
            get {
                return ResourceManager.GetString("Aria2Option_dscp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Console Color Output 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_color {
            get {
                return ResourceManager.GetString("Aria2Option_enable-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DHT (IPv4) 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_dht {
            get {
                return ResourceManager.GetString("Aria2Option_enable-dht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DHT (IPv6) 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_dht6 {
            get {
                return ResourceManager.GetString("Aria2Option_enable-dht6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable HTTP Keep-Alive 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_http_keep_alive {
            get {
                return ResourceManager.GetString("Aria2Option_enable-http-keep-alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable HTTP Pipelining 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_http_pipelining {
            get {
                return ResourceManager.GetString("Aria2Option_enable-http-pipelining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable MMap 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_mmap {
            get {
                return ResourceManager.GetString("Aria2Option_enable-mmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Peer Exchange 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_peer_exchange {
            get {
                return ResourceManager.GetString("Aria2Option_enable-peer-exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable JSON-RPC/XML-RPC Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_enable_rpc {
            get {
                return ResourceManager.GetString("Aria2Option_enable-rpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Poll Method 的本地化字符串。
        /// </summary>
        public static string Aria2Option_event_poll {
            get {
                return ResourceManager.GetString("Aria2Option_event-poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Allocation Method 的本地化字符串。
        /// </summary>
        public static string Aria2Option_file_allocation {
            get {
                return ResourceManager.GetString("Aria2Option_file-allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Metalink Files 的本地化字符串。
        /// </summary>
        public static string Aria2Option_follow_metalink {
            get {
                return ResourceManager.GetString("Aria2Option_follow-metalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Torrent Files 的本地化字符串。
        /// </summary>
        public static string Aria2Option_follow_torrent {
            get {
                return ResourceManager.GetString("Aria2Option_follow-torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Save 的本地化字符串。
        /// </summary>
        public static string Aria2Option_force_save {
            get {
                return ResourceManager.GetString("Aria2Option_force-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP Default Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passive Mode 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_pasv {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-pasv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP Proxy Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_proxy {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP Proxy Server Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_proxy_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-proxy-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP Proxy Server Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_proxy_user {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-proxy-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reuse Connection 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_reuse_connection {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-reuse-connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Type 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_type {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP Default Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ftp_user {
            get {
                return ResourceManager.GetString("Aria2Option_ftp-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash Check Only 的本地化字符串。
        /// </summary>
        public static string Aria2Option_hash_check_only {
            get {
                return ResourceManager.GetString("Aria2Option_hash-check-only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Headers 的本地化字符串。
        /// </summary>
        public static string Aria2Option_header {
            get {
                return ResourceManager.GetString("Aria2Option_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One entry per line, formatted as &quot;Header-Name: Header-Value&quot; 的本地化字符串。
        /// </summary>
        public static string Aria2Option_header_Tip {
            get {
                return ResourceManager.GetString("Aria2Option_header_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accept GZip 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_accept_gzip {
            get {
                return ResourceManager.GetString("Aria2Option_http-accept-gzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auth Challenge 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_auth_challenge {
            get {
                return ResourceManager.GetString("Aria2Option_http-auth-challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Cache 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_no_cache {
            get {
                return ResourceManager.GetString("Aria2Option_http-no-cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Default Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_http-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Proxy Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_proxy {
            get {
                return ResourceManager.GetString("Aria2Option_http-proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Proxy Server Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_proxy_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_http-proxy-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Proxy Server Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_proxy_user {
            get {
                return ResourceManager.GetString("Aria2Option_http-proxy-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Default Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_http_user {
            get {
                return ResourceManager.GetString("Aria2Option_http-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTPS Proxy Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_https_proxy {
            get {
                return ResourceManager.GetString("Aria2Option_https-proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTPS Proxy Server Password 的本地化字符串。
        /// </summary>
        public static string Aria2Option_https_proxy_passwd {
            get {
                return ResourceManager.GetString("Aria2Option_https-proxy-passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTPS Proxy Server Username 的本地化字符串。
        /// </summary>
        public static string Aria2Option_https_proxy_user {
            get {
                return ResourceManager.GetString("Aria2Option_https-proxy-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Human Readable Output 的本地化字符串。
        /// </summary>
        public static string Aria2Option_human_readable {
            get {
                return ResourceManager.GetString("Aria2Option_human-readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Unfinished Download Results 的本地化字符串。
        /// </summary>
        public static string Aria2Option_keep_unfinished_download_result {
            get {
                return ResourceManager.GetString("Aria2Option_keep-unfinished-download-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen Port 的本地化字符串。
        /// </summary>
        public static string Aria2Option_listen_port {
            get {
                return ResourceManager.GetString("Aria2Option_listen-port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log File 的本地化字符串。
        /// </summary>
        public static string Aria2Option_log {
            get {
                return ResourceManager.GetString("Aria2Option_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level 的本地化字符串。
        /// </summary>
        public static string Aria2Option_log_level {
            get {
                return ResourceManager.GetString("Aria2Option_log-level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lowest Speed Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_lowest_speed_limit {
            get {
                return ResourceManager.GetString("Aria2Option_lowest-speed-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Concurrent Downloads 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_concurrent_downloads {
            get {
                return ResourceManager.GetString("Aria2Option_max-concurrent-downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Connections Per Server 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_connection_per_server {
            get {
                return ResourceManager.GetString("Aria2Option_max-connection-per-server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Download Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_download_limit {
            get {
                return ResourceManager.GetString("Aria2Option_max-download-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Download Results 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_download_result {
            get {
                return ResourceManager.GetString("Aria2Option_max-download-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max File Not Found Tries 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_file_not_found {
            get {
                return ResourceManager.GetString("Aria2Option_max-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MMap Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_mmap_limit {
            get {
                return ResourceManager.GetString("Aria2Option_max-mmap-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Overall Download Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_overall_download_limit {
            get {
                return ResourceManager.GetString("Aria2Option_max-overall-download-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Overall Upload Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_overall_upload_limit {
            get {
                return ResourceManager.GetString("Aria2Option_max-overall-upload-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Resume Failure Tries 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_resume_failure_tries {
            get {
                return ResourceManager.GetString("Aria2Option_max-resume-failure-tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Tries 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_tries {
            get {
                return ResourceManager.GetString("Aria2Option_max-tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Upload Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_max_upload_limit {
            get {
                return ResourceManager.GetString("Aria2Option_max-upload-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base URI 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_base_uri {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-base-uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Unique Protocol 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_enable_unique_protocol {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-enable-unique-protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_language {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Server Location 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_location {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operating System 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_os {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Protocol 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_preferred_protocol {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-preferred-protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Aria2Option_metalink_version {
            get {
                return ResourceManager.GetString("Aria2Option_metalink-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Split Size 的本地化字符串。
        /// </summary>
        public static string Aria2Option_min_split_size {
            get {
                return ResourceManager.GetString("Aria2Option_min-split-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min TLS Version 的本地化字符串。
        /// </summary>
        public static string Aria2Option_min_tls_version {
            get {
                return ResourceManager.GetString("Aria2Option_min-tls-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .netrc File Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_netrc_path {
            get {
                return ResourceManager.GetString("Aria2Option_netrc-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Config File 的本地化字符串。
        /// </summary>
        public static string Aria2Option_no_conf {
            get {
                return ResourceManager.GetString("Aria2Option_no-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No File Allocation Limit 的本地化字符串。
        /// </summary>
        public static string Aria2Option_no_file_allocation_limit {
            get {
                return ResourceManager.GetString("Aria2Option_no-file-allocation-limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable netrc 的本地化字符串。
        /// </summary>
        public static string Aria2Option_no_netrc {
            get {
                return ResourceManager.GetString("Aria2Option_no-netrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Proxy Server List 的本地化字符串。
        /// </summary>
        public static string Aria2Option_no_proxy {
            get {
                return ResourceManager.GetString("Aria2Option_no-proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comma separated 的本地化字符串。
        /// </summary>
        public static string Aria2Option_no_proxy_Tip {
            get {
                return ResourceManager.GetString("Aria2Option_no-proxy_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimize Concurrent Downloads 的本地化字符串。
        /// </summary>
        public static string Aria2Option_optimize_concurrent_downloads {
            get {
                return ResourceManager.GetString("Aria2Option_optimize-concurrent-downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Parameterized URI Support 的本地化字符串。
        /// </summary>
        public static string Aria2Option_parameterized_uri {
            get {
                return ResourceManager.GetString("Aria2Option_parameterized-uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause After Metadata Download 的本地化字符串。
        /// </summary>
        public static string Aria2Option_pause_metadata {
            get {
                return ResourceManager.GetString("Aria2Option_pause-metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peer Agent 的本地化字符串。
        /// </summary>
        public static string Aria2Option_peer_agent {
            get {
                return ResourceManager.GetString("Aria2Option_peer-agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peer ID Prefix 的本地化字符串。
        /// </summary>
        public static string Aria2Option_peer_id_prefix {
            get {
                return ResourceManager.GetString("Aria2Option_peer-id-prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piece Length 的本地化字符串。
        /// </summary>
        public static string Aria2Option_piece_length {
            get {
                return ResourceManager.GetString("Aria2Option_piece-length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server Request Method 的本地化字符串。
        /// </summary>
        public static string Aria2Option_proxy_method {
            get {
                return ResourceManager.GetString("Aria2Option_proxy-method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Console Output 的本地化字符串。
        /// </summary>
        public static string Aria2Option_quiet {
            get {
                return ResourceManager.GetString("Aria2Option_quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real-time Chunk Checksum 的本地化字符串。
        /// </summary>
        public static string Aria2Option_realtime_chunk_checksum {
            get {
                return ResourceManager.GetString("Aria2Option_realtime-chunk-checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Referer 的本地化字符串。
        /// </summary>
        public static string Aria2Option_referer {
            get {
                return ResourceManager.GetString("Aria2Option_referer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Remote File Time 的本地化字符串。
        /// </summary>
        public static string Aria2Option_remote_time {
            get {
                return ResourceManager.GetString("Aria2Option_remote-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Control File 的本地化字符串。
        /// </summary>
        public static string Aria2Option_remove_control_file {
            get {
                return ResourceManager.GetString("Aria2Option_remove-control-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry Wait Time 的本地化字符串。
        /// </summary>
        public static string Aria2Option_retry_wait {
            get {
                return ResourceManager.GetString("Aria2Option_retry-wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reuse URI 的本地化字符串。
        /// </summary>
        public static string Aria2Option_reuse_uri {
            get {
                return ResourceManager.GetString("Aria2Option_reuse-uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Open File Descriptors 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rlimit_nofile {
            get {
                return ResourceManager.GetString("Aria2Option_rlimit-nofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accept All Remote Requests 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_allow_origin_all {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-allow-origin-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen on All Interfaces 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_listen_all {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-listen-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen Port 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_listen_port {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-listen-port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Request Size 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_max_request_size {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-max-request-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Uploaded Metadata 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_save_upload_metadata {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-save-upload-metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable SSL/TLS 的本地化字符串。
        /// </summary>
        public static string Aria2Option_rpc_secure {
            get {
                return ResourceManager.GetString("Aria2Option_rpc-secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Cookies Path 的本地化字符串。
        /// </summary>
        public static string Aria2Option_save_cookies {
            get {
                return ResourceManager.GetString("Aria2Option_save-cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Not Found Files 的本地化字符串。
        /// </summary>
        public static string Aria2Option_save_not_found {
            get {
                return ResourceManager.GetString("Aria2Option_save-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Session File 的本地化字符串。
        /// </summary>
        public static string Aria2Option_save_session {
            get {
                return ResourceManager.GetString("Aria2Option_save-session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Session Interval 的本地化字符串。
        /// </summary>
        public static string Aria2Option_save_session_interval {
            get {
                return ResourceManager.GetString("Aria2Option_save-session-interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Seed Ratio 的本地化字符串。
        /// </summary>
        public static string Aria2Option_seed_ratio {
            get {
                return ResourceManager.GetString("Aria2Option_seed-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Seed Time 的本地化字符串。
        /// </summary>
        public static string Aria2Option_seed_time {
            get {
                return ResourceManager.GetString("Aria2Option_seed-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Stat File 的本地化字符串。
        /// </summary>
        public static string Aria2Option_server_stat_of {
            get {
                return ResourceManager.GetString("Aria2Option_server-stat-of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Stat Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_server_stat_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_server-stat-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Console Readout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_show_console_readout {
            get {
                return ResourceManager.GetString("Aria2Option_show-console-readout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket Receive Buffer Size 的本地化字符串。
        /// </summary>
        public static string Aria2Option_socket_recv_buffer_size {
            get {
                return ResourceManager.GetString("Aria2Option_socket-recv-buffer-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections Per Task 的本地化字符串。
        /// </summary>
        public static string Aria2Option_split {
            get {
                return ResourceManager.GetString("Aria2Option_split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSH Host Key Checksum 的本地化字符串。
        /// </summary>
        public static string Aria2Option_ssh_host_key_md {
            get {
                return ResourceManager.GetString("Aria2Option_ssh-host-key-md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Stop Time 的本地化字符串。
        /// </summary>
        public static string Aria2Option_stop {
            get {
                return ResourceManager.GetString("Aria2Option_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream Piece Selector Algorithm 的本地化字符串。
        /// </summary>
        public static string Aria2Option_stream_piece_selector {
            get {
                return ResourceManager.GetString("Aria2Option_stream-piece-selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Summary Interval 的本地化字符串。
        /// </summary>
        public static string Aria2Option_summary_interval {
            get {
                return ResourceManager.GetString("Aria2Option_summary-interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_timeout {
            get {
                return ResourceManager.GetString("Aria2Option_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Truncate Console Readout 的本地化字符串。
        /// </summary>
        public static string Aria2Option_truncate_console_readout {
            get {
                return ResourceManager.GetString("Aria2Option_truncate-console-readout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URI Selector Algorithm 的本地化字符串。
        /// </summary>
        public static string Aria2Option_uri_selector {
            get {
                return ResourceManager.GetString("Aria2Option_uri-selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use HEAD Method 的本地化字符串。
        /// </summary>
        public static string Aria2Option_use_head {
            get {
                return ResourceManager.GetString("Aria2Option_use-head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom User Agent 的本地化字符串。
        /// </summary>
        public static string Aria2Option_user_agent {
            get {
                return ResourceManager.GetString("Aria2Option_user-agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Settings 的本地化字符串。
        /// </summary>
        public static string Basic_Options {
            get {
                return ResourceManager.GetString("Basic_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BitTorrent Settings 的本地化字符串。
        /// </summary>
        public static string BitTorrent_Options {
            get {
                return ResourceManager.GetString("BitTorrent_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BtDownload_Complete 的本地化字符串。
        /// </summary>
        public static string BtDownload_Complete {
            get {
                return ResourceManager.GetString("BtDownload_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to change Aria2 options 的本地化字符串。
        /// </summary>
        public static string Change_Options_Failed {
            get {
                return ResourceManager.GetString("Change_Options_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to change task files 的本地化字符串。
        /// </summary>
        public static string Change_Task_File_Failed {
            get {
                return ResourceManager.GetString("Change_Task_File_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Aria2 Updates 的本地化字符串。
        /// </summary>
        public static string Check_Aria2_Update {
            get {
                return ResourceManager.GetString("Check_Aria2_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check program update 的本地化字符串。
        /// </summary>
        public static string Check_Program_Update_Failed {
            get {
                return ResourceManager.GetString("Check_Program_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        public static string Check_Update {
            get {
                return ResourceManager.GetString("Check_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit When Main Window is Closed 的本地化字符串。
        /// </summary>
        public static string Close_To_Exit {
            get {
                return ResourceManager.GetString("Close_To_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections 的本地化字符串。
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Server 的本地化字符串。
        /// </summary>
        public static string Current_Server {
            get {
                return ResourceManager.GetString("Current_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Complete 的本地化字符串。
        /// </summary>
        public static string Download_Complete {
            get {
                return ResourceManager.GetString("Download_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Error 的本地化字符串。
        /// </summary>
        public static string Download_Error {
            get {
                return ResourceManager.GetString("Download_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Info 的本地化字符串。
        /// </summary>
        public static string Download_Info {
            get {
                return ResourceManager.GetString("Download_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Link 的本地化字符串。
        /// </summary>
        public static string Download_Link {
            get {
                return ResourceManager.GetString("Download_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple links supported, one address per line 的本地化字符串。
        /// </summary>
        public static string Download_Link_Tip {
            get {
                return ResourceManager.GetString("Download_Link_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Path 的本地化字符串。
        /// </summary>
        public static string Download_Path {
            get {
                return ResourceManager.GetString("Download_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Pause 的本地化字符串。
        /// </summary>
        public static string Download_Pause {
            get {
                return ResourceManager.GetString("Download_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Speed 的本地化字符串。
        /// </summary>
        public static string Download_Speed {
            get {
                return ResourceManager.GetString("Download_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Start 的本地化字符串。
        /// </summary>
        public static string Download_Start {
            get {
                return ResourceManager.GetString("Download_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Stop 的本地化字符串。
        /// </summary>
        public static string Download_Stop {
            get {
                return ResourceManager.GetString("Download_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded 的本地化字符串。
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate server name 的本地化字符串。
        /// </summary>
        public static string Duplicate_Server_Name {
            get {
                return ResourceManager.GetString("Duplicate_Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Aria2 Notification 的本地化字符串。
        /// </summary>
        public static string Enable_Aria2_Notification {
            get {
                return ResourceManager.GetString("Enable_Aria2_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETA 的本地化字符串。
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File List 的本地化字符串。
        /// </summary>
        public static string Files_List {
            get {
                return ResourceManager.GetString("Files_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP/SFTP Settings 的本地化字符串。
        /// </summary>
        public static string FTPSFTP_Options {
            get {
                return ResourceManager.GetString("FTPSFTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header 的本地化字符串。
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use &quot;:&quot; to separate key and value, one entry per line 的本地化字符串。
        /// </summary>
        public static string Header_Tip {
            get {
                return ResourceManager.GetString("Header_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Settings 的本地化字符串。
        /// </summary>
        public static string HTTP_Options {
            get {
                return ResourceManager.GetString("HTTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Password 的本地化字符串。
        /// </summary>
        public static string HTTP_Passwd {
            get {
                return ResourceManager.GetString("HTTP_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Username 的本地化字符串。
        /// </summary>
        public static string HTTP_User {
            get {
                return ResourceManager.GetString("HTTP_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP/FTP/SFTP Settings 的本地化字符串。
        /// </summary>
        public static string HTTPFTPSFTP_Options {
            get {
                return ResourceManager.GetString("HTTPFTPSFTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info Hash 的本地化字符串。
        /// </summary>
        public static string Info_Hash {
            get {
                return ResourceManager.GetString("Info_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Aria2 on Exit 的本地化字符串。
        /// </summary>
        public static string Kill_Aria2 {
            get {
                return ResourceManager.GetString("Kill_Aria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Aria2 when exiting the program (only affects Aria2 started by this program) 的本地化字符串。
        /// </summary>
        public static string Kill_Aria2_Tip {
            get {
                return ResourceManager.GetString("Kill_Aria2_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need restart to change language 的本地化字符串。
        /// </summary>
        public static string Language_ReStart {
            get {
                return ResourceManager.GetString("Language_ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load Aria2 options 的本地化字符串。
        /// </summary>
        public static string Load_Options_Fail {
            get {
                return ResourceManager.GetString("Load_Options_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load task stutus 的本地化字符串。
        /// </summary>
        public static string Load_Task_Status_Fail {
            get {
                return ResourceManager.GetString("Load_Task_Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Server 的本地化字符串。
        /// </summary>
        public static string Local_Server {
            get {
                return ResourceManager.GetString("Local_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetaLink 的本地化字符串。
        /// </summary>
        public static string MetaLink {
            get {
                return ResourceManager.GetString("MetaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metalink Settings 的本地化字符串。
        /// </summary>
        public static string Metalink_Options {
            get {
                return ResourceManager.GetString("Metalink_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add new Aria2 task 的本地化字符串。
        /// </summary>
        public static string New_Task_Fail {
            get {
                return ResourceManager.GetString("New_Task_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File Location 的本地化字符串。
        /// </summary>
        public static string Open_File_Location {
            get {
                return ResourceManager.GetString("Open_File_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open file location 的本地化字符串。
        /// </summary>
        public static string Open_File_Location_Failed {
            get {
                return ResourceManager.GetString("Open_File_Location_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open website 的本地化字符串。
        /// </summary>
        public static string Open_Website_Failed {
            get {
                return ResourceManager.GetString("Open_Website_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string OverView {
            get {
                return ResourceManager.GetString("OverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause All 的本地化字符串。
        /// </summary>
        public static string Pause_All {
            get {
                return ResourceManager.GetString("Pause_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to pause task 的本地化字符串。
        /// </summary>
        public static string Pause_Task_Failed {
            get {
                return ResourceManager.GetString("Pause_Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Program_Language {
            get {
                return ResourceManager.GetString("Program_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program Settings 的本地化字符串。
        /// </summary>
        public static string Program_Settings {
            get {
                return ResourceManager.GetString("Program_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Program_Theme {
            get {
                return ResourceManager.GetString("Program_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program up to date 的本地化字符串。
        /// </summary>
        public static string Program_Up_To_Date {
            get {
                return ResourceManager.GetString("Program_Up_To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program update available 的本地化字符串。
        /// </summary>
        public static string Program_Update_Available {
            get {
                return ResourceManager.GetString("Program_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Address 的本地化字符串。
        /// </summary>
        public static string Proxy_Address {
            get {
                return ResourceManager.GetString("Proxy_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Password 的本地化字符串。
        /// </summary>
        public static string Proxy_Passwd {
            get {
                return ResourceManager.GetString("Proxy_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Port 的本地化字符串。
        /// </summary>
        public static string Proxy_Port {
            get {
                return ResourceManager.GetString("Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy_Settings {
            get {
                return ResourceManager.GetString("Proxy_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Type 的本地化字符串。
        /// </summary>
        public static string Proxy_Type {
            get {
                return ResourceManager.GetString("Proxy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Username 的本地化字符串。
        /// </summary>
        public static string Proxy_User {
            get {
                return ResourceManager.GetString("Proxy_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purge All 的本地化字符串。
        /// </summary>
        public static string Purge_All {
            get {
                return ResourceManager.GetString("Purge_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to purge tasks 的本地化字符串。
        /// </summary>
        public static string Purge_Task_Failed {
            get {
                return ResourceManager.GetString("Purge_Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ratio 的本地化字符串。
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove local files? 的本地化字符串。
        /// </summary>
        public static string Remove_Local_Files {
            get {
                return ResourceManager.GetString("Remove_Local_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to remove task 的本地化字符串。
        /// </summary>
        public static string Remove_Task_Failed {
            get {
                return ResourceManager.GetString("Remove_Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume All 的本地化字符串。
        /// </summary>
        public static string Resume_All {
            get {
                return ResourceManager.GetString("Resume_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPC Settings 的本地化字符串。
        /// </summary>
        public static string RPC_Options {
            get {
                return ResourceManager.GetString("RPC_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed Ratio 的本地化字符串。
        /// </summary>
        public static string Seed_Ratio {
            get {
                return ResourceManager.GetString("Seed_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed Time 的本地化字符串。
        /// </summary>
        public static string Seed_Time {
            get {
                return ResourceManager.GetString("Seed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seeds 的本地化字符串。
        /// </summary>
        public static string Seeds {
            get {
                return ResourceManager.GetString("Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seeds/Connections 的本地化字符串。
        /// </summary>
        public static string Seeds_And_Connections {
            get {
                return ResourceManager.GetString("Seeds_And_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address 的本地化字符串。
        /// </summary>
        public static string Server_Address {
            get {
                return ResourceManager.GetString("Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Name 的本地化字符串。
        /// </summary>
        public static string Server_Name {
            get {
                return ResourceManager.GetString("Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Configuration 的本地化字符串。
        /// </summary>
        public static string Server_Options {
            get {
                return ResourceManager.GetString("Server_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Port 的本地化字符串。
        /// </summary>
        public static string Server_Port {
            get {
                return ResourceManager.GetString("Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Secret 的本地化字符串。
        /// </summary>
        public static string Server_Secret {
            get {
                return ResourceManager.GetString("Server_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Aria2 with Program 的本地化字符串。
        /// </summary>
        public static string Start_Aria2 {
            get {
                return ResourceManager.GetString("Start_Aria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use default Aria2 executable and config file 的本地化字符串。
        /// </summary>
        public static string Start_Aria2_Tip {
            get {
                return ResourceManager.GetString("Start_Aria2_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to Tray on Startup 的本地化字符串。
        /// </summary>
        public static string Start_Minimize {
            get {
                return ResourceManager.GetString("Start_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string Status_Complete {
            get {
                return ResourceManager.GetString("Status_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        public static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed 的本地化字符串。
        /// </summary>
        public static string Status_Removed {
            get {
                return ResourceManager.GetString("Status_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting 的本地化字符串。
        /// </summary>
        public static string Status_Waiting {
            get {
                return ResourceManager.GetString("Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need restart to change theme and language 的本地化字符串。
        /// </summary>
        public static string Theme_Language_ReStart {
            get {
                return ResourceManager.GetString("Theme_Language_ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need restart to change theme 的本地化字符串。
        /// </summary>
        public static string Theme_ReStart {
            get {
                return ResourceManager.GetString("Theme_ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torrent 的本地化字符串。
        /// </summary>
        public static string Torrent {
            get {
                return ResourceManager.GetString("Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trackers Source 的本地化字符串。
        /// </summary>
        public static string Trackers_Source {
            get {
                return ResourceManager.GetString("Trackers_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Interval (Days) 的本地化字符串。
        /// </summary>
        public static string Trackers_Update_Interval {
            get {
                return ResourceManager.GetString("Trackers_Update_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to unpause task 的本地化字符串。
        /// </summary>
        public static string Unpause_Task_Failed {
            get {
                return ResourceManager.GetString("Unpause_Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Trackers on Startup 的本地化字符串。
        /// </summary>
        public static string Update_BT_Trackers {
            get {
                return ResourceManager.GetString("Update_BT_Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update trackers 的本地化字符串。
        /// </summary>
        public static string Update_Trackers_Failed {
            get {
                return ResourceManager.GetString("Update_Trackers_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Speed 的本地化字符串。
        /// </summary>
        public static string Upload_Speed {
            get {
                return ResourceManager.GetString("Upload_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploaded 的本地化字符串。
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTPS 的本地化字符串。
        /// </summary>
        public static string Use_Https {
            get {
                return ResourceManager.GetString("Use_Https", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Connection 的本地化字符串。
        /// </summary>
        public static string Use_Proxy {
            get {
                return ResourceManager.GetString("Use_Proxy", resourceCulture);
            }
        }
    }
}
