//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria2Manager.WPF.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aria2Manager.WPF.Localization.WpfStrings", typeof(WpfStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Advanced_Options {
            get {
                return ResourceManager.GetString("Advanced_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled Features 的本地化字符串。
        /// </summary>
        public static string Aria2_Features {
            get {
                return ResourceManager.GetString("Aria2_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Settings 的本地化字符串。
        /// </summary>
        public static string Aria2_Options {
            get {
                return ResourceManager.GetString("Aria2_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Servers 的本地化字符串。
        /// </summary>
        public static string Aria2_Servers {
            get {
                return ResourceManager.GetString("Aria2_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Status 的本地化字符串。
        /// </summary>
        public static string Aria2_Status {
            get {
                return ResourceManager.GetString("Aria2_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Version 的本地化字符串。
        /// </summary>
        public static string Aria2_Version {
            get {
                return ResourceManager.GetString("Aria2_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Website 的本地化字符串。
        /// </summary>
        public static string Aria2_Website {
            get {
                return ResourceManager.GetString("Aria2_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Settings 的本地化字符串。
        /// </summary>
        public static string Basic_Options {
            get {
                return ResourceManager.GetString("Basic_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BitTorrent Settings 的本地化字符串。
        /// </summary>
        public static string BitTorrent_Options {
            get {
                return ResourceManager.GetString("BitTorrent_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Aria2 Updates 的本地化字符串。
        /// </summary>
        public static string Check_Aria2_Update {
            get {
                return ResourceManager.GetString("Check_Aria2_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        public static string Check_Update {
            get {
                return ResourceManager.GetString("Check_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit When Main Window is Closed 的本地化字符串。
        /// </summary>
        public static string Close_To_Exit {
            get {
                return ResourceManager.GetString("Close_To_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections 的本地化字符串。
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Server 的本地化字符串。
        /// </summary>
        public static string Current_Server {
            get {
                return ResourceManager.GetString("Current_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Info 的本地化字符串。
        /// </summary>
        public static string Download_Info {
            get {
                return ResourceManager.GetString("Download_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Link 的本地化字符串。
        /// </summary>
        public static string Download_Link {
            get {
                return ResourceManager.GetString("Download_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple links supported, one address per line 的本地化字符串。
        /// </summary>
        public static string Download_Link_Tip {
            get {
                return ResourceManager.GetString("Download_Link_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Path 的本地化字符串。
        /// </summary>
        public static string Download_Path {
            get {
                return ResourceManager.GetString("Download_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Speed 的本地化字符串。
        /// </summary>
        public static string Download_Speed {
            get {
                return ResourceManager.GetString("Download_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded 的本地化字符串。
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Aria2 Notification 的本地化字符串。
        /// </summary>
        public static string Enable_Aria2_Notification {
            get {
                return ResourceManager.GetString("Enable_Aria2_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETA 的本地化字符串。
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File List 的本地化字符串。
        /// </summary>
        public static string Files_List {
            get {
                return ResourceManager.GetString("Files_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP/SFTP Settings 的本地化字符串。
        /// </summary>
        public static string FTPSFTP_Options {
            get {
                return ResourceManager.GetString("FTPSFTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header 的本地化字符串。
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use &quot;:&quot; to separate key and value, one entry per line 的本地化字符串。
        /// </summary>
        public static string Header_Tip {
            get {
                return ResourceManager.GetString("Header_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Settings 的本地化字符串。
        /// </summary>
        public static string HTTP_Options {
            get {
                return ResourceManager.GetString("HTTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Password 的本地化字符串。
        /// </summary>
        public static string HTTP_Passwd {
            get {
                return ResourceManager.GetString("HTTP_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP Username 的本地化字符串。
        /// </summary>
        public static string HTTP_User {
            get {
                return ResourceManager.GetString("HTTP_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP/FTP/SFTP Settings 的本地化字符串。
        /// </summary>
        public static string HTTPFTPSFTP_Options {
            get {
                return ResourceManager.GetString("HTTPFTPSFTP_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info Hash 的本地化字符串。
        /// </summary>
        public static string Info_Hash {
            get {
                return ResourceManager.GetString("Info_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Aria2 on Exit 的本地化字符串。
        /// </summary>
        public static string Kill_Aria2 {
            get {
                return ResourceManager.GetString("Kill_Aria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Aria2 when exiting the program (only affects Aria2 started by this program) 的本地化字符串。
        /// </summary>
        public static string Kill_Aria2_Tip {
            get {
                return ResourceManager.GetString("Kill_Aria2_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Server 的本地化字符串。
        /// </summary>
        public static string Local_Server {
            get {
                return ResourceManager.GetString("Local_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetaLink 的本地化字符串。
        /// </summary>
        public static string MetaLink {
            get {
                return ResourceManager.GetString("MetaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metalink Settings 的本地化字符串。
        /// </summary>
        public static string Metalink_Options {
            get {
                return ResourceManager.GetString("Metalink_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File Location 的本地化字符串。
        /// </summary>
        public static string Open_File_Location {
            get {
                return ResourceManager.GetString("Open_File_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string OverView {
            get {
                return ResourceManager.GetString("OverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause All 的本地化字符串。
        /// </summary>
        public static string Pause_All {
            get {
                return ResourceManager.GetString("Pause_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Program_Language {
            get {
                return ResourceManager.GetString("Program_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program Settings 的本地化字符串。
        /// </summary>
        public static string Program_Settings {
            get {
                return ResourceManager.GetString("Program_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Program_Theme {
            get {
                return ResourceManager.GetString("Program_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Address 的本地化字符串。
        /// </summary>
        public static string Proxy_Address {
            get {
                return ResourceManager.GetString("Proxy_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Password 的本地化字符串。
        /// </summary>
        public static string Proxy_Passwd {
            get {
                return ResourceManager.GetString("Proxy_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Port 的本地化字符串。
        /// </summary>
        public static string Proxy_Port {
            get {
                return ResourceManager.GetString("Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy_Settings {
            get {
                return ResourceManager.GetString("Proxy_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Type 的本地化字符串。
        /// </summary>
        public static string Proxy_Type {
            get {
                return ResourceManager.GetString("Proxy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Username 的本地化字符串。
        /// </summary>
        public static string Proxy_User {
            get {
                return ResourceManager.GetString("Proxy_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purge All 的本地化字符串。
        /// </summary>
        public static string Purge_All {
            get {
                return ResourceManager.GetString("Purge_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ratio 的本地化字符串。
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume All 的本地化字符串。
        /// </summary>
        public static string Resume_All {
            get {
                return ResourceManager.GetString("Resume_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPC Settings 的本地化字符串。
        /// </summary>
        public static string RPC_Options {
            get {
                return ResourceManager.GetString("RPC_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed Ratio 的本地化字符串。
        /// </summary>
        public static string Seed_Ratio {
            get {
                return ResourceManager.GetString("Seed_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seed Time 的本地化字符串。
        /// </summary>
        public static string Seed_Time {
            get {
                return ResourceManager.GetString("Seed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seeds 的本地化字符串。
        /// </summary>
        public static string Seeds {
            get {
                return ResourceManager.GetString("Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seeds/Connections 的本地化字符串。
        /// </summary>
        public static string Seeds_And_Connections {
            get {
                return ResourceManager.GetString("Seeds_And_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address 的本地化字符串。
        /// </summary>
        public static string Server_Address {
            get {
                return ResourceManager.GetString("Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Name 的本地化字符串。
        /// </summary>
        public static string Server_Name {
            get {
                return ResourceManager.GetString("Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Configuration 的本地化字符串。
        /// </summary>
        public static string Server_Options {
            get {
                return ResourceManager.GetString("Server_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Port 的本地化字符串。
        /// </summary>
        public static string Server_Port {
            get {
                return ResourceManager.GetString("Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Secret 的本地化字符串。
        /// </summary>
        public static string Server_Secret {
            get {
                return ResourceManager.GetString("Server_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Aria2 with Program 的本地化字符串。
        /// </summary>
        public static string Start_Aria2 {
            get {
                return ResourceManager.GetString("Start_Aria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use default Aria2 executable and config file 的本地化字符串。
        /// </summary>
        public static string Start_Aria2_Tip {
            get {
                return ResourceManager.GetString("Start_Aria2_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to Tray on Startup 的本地化字符串。
        /// </summary>
        public static string Start_Minimize {
            get {
                return ResourceManager.GetString("Start_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string TaskStatus_Active {
            get {
                return ResourceManager.GetString("TaskStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string TaskStatus_All {
            get {
                return ResourceManager.GetString("TaskStatus_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string TaskStatus_Stopped {
            get {
                return ResourceManager.GetString("TaskStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting 的本地化字符串。
        /// </summary>
        public static string TaskStatus_Waiting {
            get {
                return ResourceManager.GetString("TaskStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torrent 的本地化字符串。
        /// </summary>
        public static string Torrent {
            get {
                return ResourceManager.GetString("Torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trackers Source 的本地化字符串。
        /// </summary>
        public static string Trackers_Source {
            get {
                return ResourceManager.GetString("Trackers_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Interval (Days) 的本地化字符串。
        /// </summary>
        public static string Trackers_Update_Interval {
            get {
                return ResourceManager.GetString("Trackers_Update_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Trackers on Startup 的本地化字符串。
        /// </summary>
        public static string Update_BT_Trackers {
            get {
                return ResourceManager.GetString("Update_BT_Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Speed 的本地化字符串。
        /// </summary>
        public static string Upload_Speed {
            get {
                return ResourceManager.GetString("Upload_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploaded 的本地化字符串。
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTPS 的本地化字符串。
        /// </summary>
        public static string Use_Https {
            get {
                return ResourceManager.GetString("Use_Https", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Connection 的本地化字符串。
        /// </summary>
        public static string Use_Proxy {
            get {
                return ResourceManager.GetString("Use_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
